<template>
  <div class="bg-effects-container">
    <!-- GENERATING STATE -->
    <div v-if="isGenerating" class="generating-overlay">
      <div class="scanner-line"></div>
      <div class="generating-text">
        <span class="blink">GENERATING_UNIQUE_BACKGROUND...</span>
        <div class="progress-bar"><div class="progress-fill"></div></div>
      </div>
    </div>

    <!-- AI-GENERATED BACKGROUND -->
    <div v-else-if="role?.backgroundSvg" class="svg-container" v-html="sanitizedSvg"></div>

    <!-- FALLBACK (no SVG yet) -->
    <svg v-else class="bg-svg fallback" viewBox="0 0 1000 1000" preserveAspectRatio="xMidYMid slice">
      <circle cx="500" cy="500" r="200" fill="none" stroke="currentColor" stroke-width="2" class="draw-path"/>
      <circle cx="500" cy="500" r="300" fill="none" stroke="currentColor" stroke-width="1" opacity="0.5" class="rotate-slow"/>
    </svg>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue'

const props = defineProps<{
  role: any
}>()

const isGenerating = ref(false)
let timer: any = null

onMounted(() => {
  // Show generating animation briefly when entering a new chat
  // This creates anticipation even though SVG is already generated
  if (props.role && !props.role.backgroundSvg) {
    isGenerating.value = true
    timer = setTimeout(() => {
      isGenerating.value = false
    }, 2000)
  }
})

onUnmounted(() => {
  if (timer) clearTimeout(timer)
})

// Sanitize the SVG to ensure it has the right class for styling
const sanitizedSvg = computed(() => {
  if (!props.role?.backgroundSvg) return ''
  
  let svg = props.role.backgroundSvg
  
  // Add bg-svg class if not present
  if (!svg.includes('class="bg-svg"') && !svg.includes("class='bg-svg'")) {
    svg = svg.replace('<svg', '<svg class="bg-svg"')
  }

  // CRITICAL FIX: Remove hardcoded background styles generated by AI
  // Some SVGs come with style="background: black" or background-color: #000
  svg = svg.replace(/style="[^"]*background[^"]*"/gi, '')
  svg = svg.replace(/style='[^']*background[^']*'/gi, '')
  
  return svg
})
</script>

<style scoped>
.bg-effects-container {
  position: absolute;
  inset: 0;
  pointer-events: none;
  overflow: hidden;
  z-index: 0;
  color: #1d1d1f;
  opacity: 0.15;
}

.svg-container {
  width: 100%;
  height: 100%;
}

.svg-container :deep(.bg-svg),
.bg-svg {
  width: 100%;
  height: 100%;
}

/* Generating UI */
.generating-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(5px);
  z-index: 10;
}

.scanner-line {
  width: 100%;
  height: 2px;
  background: linear-gradient(90deg, transparent, #1d1d1f, transparent);
  position: absolute;
  top: 30%;
  animation: scan 2s ease-in-out infinite;
  opacity: 0.5;
}

.generating-text {
  font-family: 'Courier New', monospace;
  font-size: 14px;
  color: #333;
  letter-spacing: 3px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 15px;
}

.progress-bar {
  width: 250px;
  height: 3px;
  background: #ddd;
  overflow: hidden;
}

.progress-fill {
  width: 100%;
  height: 100%;
  background: #1d1d1f;
  transform-origin: 0 50%;
  animation: progress 2s ease-out forwards;
}

@keyframes scan {
  0% { top: 30%; opacity: 0; }
  50% { opacity: 0.6; }
  100% { top: 70%; opacity: 0; }
}

@keyframes progress {
  0% { transform: scaleX(0); }
  100% { transform: scaleX(1); }
}

.blink {
  animation: blink 0.5s infinite alternate;
}

@keyframes blink {
  from { opacity: 0.5; }
  to { opacity: 1; }
}

/* Animation classes for AI-generated SVGs */
.svg-container :deep(.rotate-slow),
.rotate-slow {
  animation: rotate 60s linear infinite;
  transform-origin: center center;
}

.svg-container :deep(.rotate-fast),
.rotate-fast {
  animation: rotate 20s linear infinite;
  transform-origin: center center;
}

.svg-container :deep(.float),
.float {
  animation: float 8s ease-in-out infinite;
}

.svg-container :deep(.pulse),
.pulse {
  animation: pulse 3s ease-in-out infinite;
}

.svg-container :deep(.draw-path),
.draw-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
  animation: draw 4s ease-out forwards;
}

@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

@keyframes float {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-20px); }
}

@keyframes pulse {
  0%, 100% { opacity: 0.5; }
  50% { opacity: 1; }
}

@keyframes draw {
  to { stroke-dashoffset: 0; }
}
</style>
